import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Anaïs Carlier | Naturopathe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // bg-[#FCF9F6]
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen bg-gradient-to-tr from-lime-50 to-slate-50pnpm`}
      >
        {children}
      </body>
    </html>
  );
}
